on:
    push:
        branches:
            - main

jobs:
    prerelease:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Make prerelease to npm
              uses: esamattis/npm-release@v1
              with:
                  type: prerelease
                  token: ${{ secrets.CAZOO_NPM_TOKEN }}
